### ISSUE TITLE
Yarn 1.7 required by XO 5.20.x

### ISSUE THREAD

**Issue by Danp2** [Jarli01/xenorchestra_updater#17]
#### Expected Behavior

Update script to pull down latest version of Yarn

-----

#### Actual Behavior

>Checking for Yarn package...
Checking for Yarn update...
Reading package lists... Done
Building dependency tree
Reading state information... Done
yarn is already the newest version (1.6.0-1)

-----

**Comment by Danp2** [comment]
Resolved issue by restoring access to Yarn repo, which was disabled to upgrade to Ubuntu 18.04.

**Comment by Jarli01** [comment]
Was this an issue with the updater or something local to your installation?

**Comment by Danp2** [comment]
It was an issue outside of this script. However, others could encounter this same issue if they forget to reenable the repo in `/etc/apt/sources.list.d/yarn.list` after running the Ubuntu upgrade process.
