### ISSUE TITLE
after Updating (via Script) GUI login does not work

### ISSUE THREAD

**Issue by BerT666** [Jarli01/xenorchestra_updater#18]
#### Expected Behavior

GUI Login should be possible

-----

#### Actual Behavior

No User can login (also admin)

-----
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade via script
- Version of XOCE server and web interface you're running 5.26.0
- What OS is XOCE running on? Ubuntu 16.4.5 LTS
- What method you used to install XOCE (xo_install.sh, manual installation, etc) xo-install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error Login page
- Any errors that appear in your browser's error console. Invalid Credentials
- Include what you've done so far in the installation, and if you got any error messages along the way. Worked until ~17.09.2018, afterwards the update via script fails
- Indicate whether or not you've manually edited any data directly. no manual editing

**Comment by Jarli01** [comment]
So you can get to the login page, but are unable to login?

Also please provide answers to the following. 

Confirm XOCE services are running
systemctl status xo-server.service

Provide the output of journalctl logs
journalctl -u xo-server -f -n 50

**Comment by Jarli01** [comment]
[This process is from 2016](https://xen-orchestra.com/forum/topic/126/reset-password-of-particular-user/5) but it likely still works to reset the local admin password via SSH to your server. 

As there isn't anything in the update script that changes passwords I'd imagine someone has changed your password on you. 

I'll test on a system here in a bit and see what happens with the password reset process.

**Comment by BerT666** [comment]
Ok, I have re-run the update, but something is still wrong :-(
Login with AD-User is now working (Admin Role), but there is no config :-(
(local) Admin Login still fails... [ ssh still working ]

As Workaround I will not try to update...

This is reproducible (Snapshot / Revert) and seems to break everytime I run the Update via CLI => I doubt it is a "real" password change

systemctl status xo-server.service:
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Mi 2018-09-19 16:24:08 CEST; 41s ago
 Main PID: 31410 (node)
    Tasks: 17
   Memory: 132.8M
      CPU: 3.791s
   CGroup: /system.slice/xo-server.service
           ├─31410 /usr/local/bin/node ./bin/xo-server
           └─31425 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/child.js

Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.200Z xo:plugin successfully register load-balancer
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.205Z xo:plugin successfully register usage-report
Sep 19 16:24:13 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 950 ms
Sep 19 16:24:14 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 1040 ms
Sep 19 16:24:15 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 2005 ms
Sep 19 16:24:17 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 2991 ms
Sep 19 16:24:20 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 5246 ms
Sep 19 16:24:25 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 7890 ms
Sep 19 16:24:33 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 12937 ms
Sep 19 16:24:46 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 20453 ms

journalctl -u xo-server -f -n 50
-- Logs begin at Mi 2018-09-19 15:10:39 CEST. --
Sep 19 16:24:13 xoa2 xo-server[31410]:     at process._tickCallback (internal/process/next_tick.js:112:11)
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.151Z xo:perf blocked for 1424ms
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.191Z xo:plugin successfully register auth-google
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.192Z xo:plugin successfully register auth-saml
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.192Z xo:plugin successfully register perf-alert
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.192Z xo:plugin successfully register test-plugin
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.193Z xo:plugin successfully register transport-nagios
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.193Z xo:plugin successfully register transport-slack
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.193Z xo:plugin successfully register transport-xmpp
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.194Z xo:plugin successfully register cloud
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.199Z xo:plugin successfully register auth-ldap
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.199Z xo:plugin successfully register backup-reports
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.199Z xo:plugin successfully register transport-email
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.200Z xo:plugin successfully register load-balancer
Sep 19 16:24:13 xoa2 xo-server[31410]: 2018-09-19T14:24:13.205Z xo:plugin successfully register usage-report
Sep 19 16:24:13 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 950 ms
Sep 19 16:24:14 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 1040 ms
Sep 19 16:24:15 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 2005 ms
Sep 19 16:24:17 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 2991 ms
Sep 19 16:24:20 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 5246 ms
Sep 19 16:24:25 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 7890 ms
Sep 19 16:24:33 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 12937 ms
Sep 19 16:24:46 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 20453 ms
Sep 19 16:25:00 xoa2 xo-server[31410]: [load-balancer]Execute plans!
Sep 19 16:25:00 xoa2 xo-server[31410]: [load-balancer]No hosts to optimize.
Sep 19 16:25:06 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 32513 ms
Sep 19 16:25:39 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 52532 ms
Sep 19 16:25:42 xoa2 xo-server[31410]: 2018-09-19T14:25:42.040Z xo:main + WebSocket connection (::ffff:192.168.66.6)
Sep 19 16:26:00 xoa2 xo-server[31410]: [load-balancer]Execute plans!
Sep 19 16:26:00 xoa2 xo-server[31410]: [load-balancer]No hosts to optimize.
Sep 19 16:26:31 xoa2 xo-server[31410]: xo-server-cloud: fail to connect to updater ConnectionError: connect ECONNREFUSED 127.0.0.1:9001
Sep 19 16:26:31 xoa2 xo-server[31410]:     at /opt/xen-orchestra/node_modules/jsonrpc-websocket-client/src/websocket-client.js:193:16
Sep 19 16:26:31 xoa2 xo-server[31410]:     at run (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:75:22)
Sep 19 16:26:31 xoa2 xo-server[31410]:     at /opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:92:30
Sep 19 16:26:31 xoa2 xo-server[31410]:     at flush (/opt/xen-orchestra/node_modules/core-js/modules/_microtask.js:18:9)
Sep 19 16:26:31 xoa2 xo-server[31410]:     at process._tickCallback (internal/process/next_tick.js:112:11)
Sep 19 16:26:31 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 1049 ms
Sep 19 16:26:32 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 1028 ms
Sep 19 16:26:33 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 1956 ms
Sep 19 16:26:35 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 3104 ms
Sep 19 16:26:38 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 5147 ms
Sep 19 16:26:44 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 7875 ms
Sep 19 16:26:51 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 13314 ms
Sep 19 16:27:00 xoa2 xo-server[31410]: [load-balancer]Execute plans!
Sep 19 16:27:00 xoa2 xo-server[31410]: [load-balancer]No hosts to optimize.
Sep 19 16:27:05 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 20787 ms
Sep 19 16:27:26 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 32367 ms
Sep 19 16:27:58 xoa2 xo-server[31410]: xo-server-cloud: next attempt in 53583 ms
Sep 19 16:28:00 xoa2 xo-server[31410]: [load-balancer]Execute plans!
Sep 19 16:28:00 xoa2 xo-server[31410]: [load-balancer]No hosts to optimize.

**Comment by Danp2** [comment]
I am not experiencing this issue. I wonder if it is related to logging in with AD. Another person recently had [similar issue](https://xen-orchestra.com/forum/topic/1161/lost-menu-s-after-update), and they aren't using these scripts so it may be another more generic issue.

Have you tried exporting the config from the "good" snapshot and then reimporting the settings after upgrading?

**Comment by Jarli01** [comment]
So I just ran a clean installation and the default credentials don't work. . .

**Comment by Jarli01** [comment]
The password reset process from their forums doesn't appear to work (at least not out of the box)

	 /usr/lib/node_modules/hashy/cli.js

	> argon2@0.19.3 install /usr/lib/node_modules/hashy/node_modules/argon2
	> node-gyp rebuild

	gyp ERR! configure error
	gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ha                                                                                                                                                             shy/node_modules/argon2/build'
	gyp ERR! System Linux 4.15.0-34-generic
	gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy                                                                                                                                                             p/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /usr/lib/node_modules/hashy/node_modules/argon2
	gyp ERR! node -v v8.12.0
	gyp ERR! node-gyp -v v3.8.0
	gyp ERR! not ok

	> bcrypt@2.0.1 install /usr/lib/node_modules/hashy/node_modules/bcrypt
	> node-pre-gyp install --fallback-to-build

	node-pre-gyp ERR! Pre-built binaries not installable for bcrypt@2.0.1 and node@8                                                                                                                                                             .12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
	node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/usr/lib/node_modu                                                                                                                                                             les/hashy/node_modules/bcrypt/lib'
	gyp ERR! configure error
	gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/ha                                                                                                                                                             shy/node_modules/bcrypt/build'
	gyp ERR! System Linux 4.15.0-34-generic
	gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy                                                                                                                                                             p/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/lib/node_mod                                                                                                                                                             ules/hashy/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcryp                                                                                                                                                             t_lib" "--module_path=/usr/lib/node_modules/hashy/node_modules/bcrypt/lib/bindin                                                                                                                                                             g" "--napi_version=3" "--node_abi_napi=napi"
	gyp ERR! cwd /usr/lib/node_modules/hashy/node_modules/bcrypt
	gyp ERR! node -v v8.12.0
	gyp ERR! node-gyp -v v3.8.0
	gyp ERR! not ok
	node-pre-gyp ERR! build error
	node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_mo                                                                                                                                                             dules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --                                                                                                                                                             module=/usr/lib/node_modules/hashy/node_modules/bcrypt/lib/binding/bcrypt_lib.no                                                                                                                                                             de --module_name=bcrypt_lib --module_path=/usr/lib/node_modules/hashy/node_modul                                                                                                                                                             es/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
	node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/h                                                                                                                                                             ashy/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
	node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
	node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
	node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
	node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi                                                                                                                                                             ld_process.js:209:5)
	node-pre-gyp ERR! System Linux 4.15.0-34-generic
	node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/hashy/node_modu                                                                                                                                                             les/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
	node-pre-gyp ERR! cwd /usr/lib/node_modules/hashy/node_modules/bcrypt
	node-pre-gyp ERR! node -v v8.12.0
	node-pre-gyp ERR! node-pre-gyp -v v0.9.1
	node-pre-gyp ERR! not ok
	Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp                                                                                                                                                             /bin/node-gyp.js configure --fallback-to-build --module=/usr/lib/node_modules/ha                                                                                                                                                             shy/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --m                                                                                                                                                             odule_path=/usr/lib/node_modules/hashy/node_modules/bcrypt/lib/binding --napi_ve                                                                                                                                                             rsion=3 --node_abi_napi=napi' (1)
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: argon2@0.19.3 (node_modules/hash                                                                                                                                                             y/node_modules/argon2):
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: argon2@0.19.3 install: `node-gyp                                                                                                                                                              rebuild`
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@2.0.1 (node_modules/hashy                                                                                                                                                             /node_modules/bcrypt):
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bcrypt@2.0.1 install: `node-pre-                                                                                                                                                             gyp install --fallback-to-build`
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

	+ hashy@0.7.1
	added 62 packages from 17 contributors in 8.043s

**Comment by Danp2** [comment]
> 
> 
> So I just ran a clean installation and the default credentials don't work. . .

Try resetting the database --
```
    redis-cli
    FLUSHALL
    systemctl restart xo-server.service
```

**Comment by Jarli01** [comment]
No change.

**Comment by Danp2** [comment]
I'll do some testing on this end. I'm wondering recent commits have introduced an issue and building using the 5.26.0 source would allow a successful login.

This all brings me back around this the following --
https://github.com/Jarli01/xenorchestra_installer/issues/17

**Comment by Jarli01** [comment]
This change would also affect people building from the source. I don't disagree that having the option to specify a tag to build from would be a good thing. 

Just asking why now has this occurred. If the installation script didn't exist than others

**Comment by BerT666** [comment]
Hi, as I cannot log in with admin (and the ad user seems to be degraded to user role), the import of the config to the "bad/updated" version, is a bit problematic. Have not done a config import from cli...

**Comment by Danp2** [comment]
I opened an issue on the XO repo --

https://github.com/vatesfr/xen-orchestra/issues/3431

**Comment by BerT666** [comment]
this morning I saw that this should be solved ;-)
I ran an update (after a new Snapshot) and now the update works and the login afterwards is still good ;-)

Thanks a lot!

**Comment by Jarli01** [comment]
Closing per your comment and the fact that this issue has been resolved by the upstream team.
