### ISSUE TITLE
5.41 update from 5.39 leaves issues with certain pages.

### ISSUE THREAD

**Issue by astrugatch** [Jarli01/xenorchestra_updater#22]
#### Expected Behavior

After update Plugins, Backup and Backup-NG should be accessible

-----

#### Actual Behavior

after update(pulled 5.41)  get "page not found" for those pages

-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade
- Version of XOCE server and web interface you're running they moved to 5.41 but i've rolled back to a 5.39 snapshot
- What OS is XOCE running on? Ubuntu 18.04 LTS
- What method you used to install XOCE (xo_install.sh, manual installation, etc) xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error - home page trying to load plugins, backup or backup-ng
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Include what you've done so far in the installation, and if you got any error messages along the way. the update was fresh. Pretty basic install, connected to one host, with a handful of VMS using backup NG, did the update because the email plugin hasnt been working. Have since rolled back because I need those panes more than the email.
- Indicate whether or not you've manually edited any data directly.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Danp2** [comment]
- Please check your node version with `node -v` to ensure that you are still on v8.x.
- There is information missing from your report
   - Output from `systemctl status xo-server.service`
   - Output from `journalctl -u xo-server -f -n 50`
   - Console output from when you ran the upgrade process

**Comment by Danp2** [comment]
According to the post [here](https://xcp-ng.org/forum/post/11991), this was caused by an issue with the XO source and has nothing to do with this script.
