### ISSUE TITLE
Web interface running an older version of Xen Orchestra.

### ISSUE THREAD

**Issue by dobrosavljevic** [Jarli01/xenorchestra_updater#30]
#### Expected Behavior

Loading the web interface should run the latest version of Xen Orchestra (currently at 5.55.0). 

-----

#### Actual Behavior

We hadn't updated our Xen Orchestra install since 5.42.1 and decided to do it around the 5.54.0 mark. Running the update scripts seems to work correctly. It doesn't error out and it recognizes that we've run the update script before and it gives us the correct current version of the software if we rerun the update script after just successfully updating it but going to the web interface it still seems to be running the 5.42.1 version. The about page states that it's running xo-server 5.42.1 and xo-web 5.42.1.

-----

#### Confirm XOCE services are running

Active: active (running)

#### Provide the output of journalctl logs

-- Logs begin at Fri 2020-01-24 11:26:21 CST. --
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         [Object],
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         [Object],
Jan 24 11:32:50 xo xo-server[2356]:         [Object],
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         [Object],
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {},
Jan 24 11:32:50 xo xo-server[2356]:         CallSite {} ] } }
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.846Z - xo:perf - [INFO] blocked for 1800ms
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.945Z - xo:plugin - [INFO] successfully register auth-google
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.945Z - xo:plugin - [INFO] successfully register auth-ldap
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.945Z - xo:plugin - [INFO] successfully register auth-saml
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.946Z - xo:plugin - [INFO] successfully register load-balancer
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.946Z - xo:plugin - [INFO] successfully register perf-alert
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.946Z - xo:plugin - [INFO] successfully register sdn-controller
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.946Z - xo:plugin - [INFO] successfully register test-plugin
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.947Z - xo:plugin - [INFO] successfully register transport-icinga2
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.947Z - xo:plugin - [INFO] successfully register transport-nagios
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.947Z - xo:plugin - [INFO] successfully register transport-slack
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.947Z - xo:plugin - [INFO] successfully register transport-xmpp
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.947Z - xo:plugin - [INFO] successfully register usage-report
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.947Z - xo:plugin - [INFO] successfully register web-hooks
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.948Z - xo:plugin - [INFO] successfully register backup-reports
Jan 24 11:32:50 xo xo-server[2356]: 2020-01-24T17:32:50.948Z - xo:plugin - [INFO] successfully register transport-email
Jan 24 11:33:15 xo xo-server[2356]: 2020-01-24T17:33:15.218Z - xo:main - [INFO] + WebSocket connection
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of XOCE server and web interface you're running: The upgrade script says 5.55.0 but the web interface says 5.42.1
- What OS is XOCE running on? Ubuntu 16.04.6 LTS
- What method you used to install XOCE (xo_install.sh, manual installation, etc) xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error: N/A
- If a stacktrace is provided in the error, include that too.: N/A
- Any errors that appear in your browser's error console.: N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.: N/A
- Indicate whether or not you've manually edited any data directly.: No manual editing of any data.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
Are you getting prompted during the upgrade to identify yourself for git? 

As a side note, 16.04.6 is ancient and you could easily install on a current OS that is still being updated.

**Comment by dobrosavljevic** [comment]
I was getting prompted at first but I've done the registration part and it's actually letting me update things correctly. Like I said the scripts actually say that I am running the latest version. It's only when I get to the web interface that the About page says it's still running the old version.

I don't mind upgrading to a newer Ubuntu release either, I just didn't think that would have made a difference with this particular issue.

I guess now that I am talking through it this might be a XO issue rather then an update script issue.

**Comment by Jarli01** [comment]
If you wanted to put the full update process into pastebin I could take a look, but generally speaking when you get stuck on a version, it's always been that you haven't identified with git. 

But also being on such an old OS isn't going to help you in the long haul.

**Comment by dobrosavljevic** [comment]
Alright, I'll update Ubuntu first and see where that gets me. Is there a spot I could get the past update logs from or would you want me to just rerun the update script and get you the messages that I get back from that if I am still stugling with this after Ubuntu has been upgraded?

**Comment by Jarli01** [comment]
I've always done updates over ssh, so would have them in my session to just scroll back and review. You could roll back, and reattempt the update to show it.

**Comment by dobrosavljevic** [comment]
*facepalm* I've had an SSH session going:

https://pastebin.com/NDnzympi

**Comment by dobrosavljevic** [comment]
Rerunning the script now I get:

Stopping xo-server...
Checking for Yarn package...
Checking for Yarn update...
OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
yarn is already the newest version (1.21.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking for missing dependencies...
Checking for Repo change...
Checking xen-orchestra...
Current branch master
Current version 5.55.0 / 5.55.0
0 updates available
Restarting xo-server...

**Comment by Jarli01** [comment]
Just for laughs have you restarted the server? Maybe something is hung. From the logs I'm not seeing anything that stands out. 

Another thought is maybe this information is cache, try an incognito window.

**Comment by dobrosavljevic** [comment]
Yea, tried the basic stuff already.

Upgrading to 18.04.3 didn't seem to have made a difference either. Could it be that I have both versions running in parallel on here and the old version is just the one that responds to web requests? Do you know what web server XO is using so I can check the configuration settings? Can't find an instance of either Apache or Nginx running on here.

**Comment by Jarli01** [comment]
You did an inline upgrade rather than a parallel build?

**Comment by dobrosavljevic** [comment]
Is that a separate option? I tried both the basic upgrade and a force rebuild upgrade and got the same result.

**Comment by Jarli01** [comment]
What I would do is setup a new VM running 18.04 or 19.10 and go through the installation process. A completely clean environment. 

XO is meant to be disposable, so once your new installation is up, transfer your backup schedule and move on with your day.

**Comment by dobrosavljevic** [comment]
Ugghhh, why do you have to make so much sense?

Thank you so much for your help.

**Comment by Jarli01** [comment]
Let me know if you hit any issues from there, but honestly, something so far out of date is a lost cause imo. 

lol

**Comment by Jarli01** [comment]
And by transfer your backup schedule I mean, just export the config file, and import it in the new installation. 

:-)

**Comment by dobrosavljevic** [comment]
I see the export option under Settings -> Config. Where is the import option?

**Comment by dobrosavljevic** [comment]
Ahhh, it might be there on the newest version of XO and I am just not seeing it in the old.

**Comment by Jarli01** [comment]
That version absolutely should have it there. . . unless you built with a really early version of this script which didn't have that enabled.

**Comment by dobrosavljevic** [comment]
I am pretty sure that's the case.

**Comment by Jarli01** [comment]
Anyways, build a new installation and try and import your configuration. It should handle everything for you, reconnecting to your servers, setting up your backup schedule etc.
