### ISSUE TITLE
Cant remove xo-server-test after latest commit.

### ISSUE THREAD

**Issue by MDE186** [Jarli01/xenorchestra_updater#32]
After the latest commit ( https://github.com/Jarli01/xenorchestra_updater/commit/12c15f64472f1f751151f5d0384f90b275606c4a) and running the update script the below is shown as the last line

```
Removing link for xo-server-test
rm: cannot remove '/usr/local/lib/node_modulesxo-server-test': No such file or directory

```
I think it's just missing a " / ".

As can be seen, the files still exist

```
root@xxx:/home/xxx# cd /usr/local/lib/node_modules
root@xxx:/usr/local/lib/node_modules# ls
npm                    xo-server-auth-ldap       xo-server-perf-alert      xo-server-transport-email    xo-server-transport-xmpp
xo-server-audit        xo-server-auth-saml       xo-server-sdn-controller  xo-server-transport-icinga2  xo-server-usage-report
xo-server-auth-github  xo-server-backup-reports  xo-server-test            xo-server-transport-nagios   xo-server-web-hooks
xo-server-auth-google  xo-server-load-balancer   xo-server-test-plugin     xo-server-transport-slack
```
Many thanks.

**Comment by MDE186** [comment]
https://github.com/Jarli01/xenorchestra_updater/commit/12c15f64472f1f751151f5d0384f90b275606c4a

**Comment by Jarli01** [comment]
I'm testing now to see where this might be. 

@Danp2 I confirmed those changes and I don't see any error in there.

**Comment by Danp2** [comment]
Looks like I left out a slash character between the two variables. I've pushes a fix. Please retest at your convenience.

**Comment by Danp2** [comment]
Updated earlier using the revised version and it ran as expected.
