### ISSUE TITLE
Updater Script - Minimum Memory

### ISSUE THREAD

**Issue by MDE186** [Jarli01/xenorchestra_updater#36]
#### Expected Behavior

The script to operate with 3GB of memory.

-----

#### Actual Behavior

If the VM has 3GB of memory I get the error: "XOCE Requires at least 3GB Memory!"
If I upgrade the VM to 4GB memory it works.

Should the script view it as 3GB available memory? or Total Memory?

Obviously related to commit [LINK](https://github.com/Jarli01/xenorchestra_updater/commit/290db729000df107c92df04b87dfe77015812d80)

-----

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - UPDATE
- Version of XOCE server and web interface you're running 5.60
- What OS is XOCE running on? Debian 10
- What method you used to install XOCE (xo_install.sh, manual installation, etc) - Updater script.
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error. Running the updater script.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly. - NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
On your VM with 3GB of ram can you post the output of ```awk '/^MemTotal:/{print $2}' /proc/meminfo```

**Comment by Danp2** [comment]
@Jarli01 Just beat me to it. I was going to suggest that you run the command `cat /proc/meminfo | grep MemTotal` and post the resulting output

**Comment by Jarli01** [comment]
The script technically checks for the lowest amount of ram possible for the installation. The installation doesn't check that the ram is freely available, just that it's installed.

**Comment by MDE186** [comment]
Hi, thanks for getting back so quick.

xoa@xoa:~$ cat /proc/meminfo | grep MemTotal
MemTotal:        3043420 kB

**Comment by Danp2** [comment]
That's what I was guessing. I seem to recall running into something similar previously and "resetting" the memory resolved it

**Comment by Jarli01** [comment]
Great, glad this was easily resolved.
