### ISSUE TITLE
Unable to resolve reference -- reference broken

### ISSUE THREAD

**Issue by kevdogg** [Jarli01/xenorchestra_updater#37]
#### Expected Behavior

Updater script to update -- as it actually has successfully for about the last year

-----

#### Actual Behavior

```
sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5569  100  5569    0     0  30431      0 --:--:-- --:--:-- --:--:-- 30431
Stopping xo-server...
Checking for Yarn package...
Checking for Yarn update...
OK
Reading package lists... Done
Building dependency tree
Reading state information... Done
yarn is already the newest version (1.22.4-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking for missing dependencies...
Checking for Repo change...
Checking xen-orchestra...
Current branch master
Current version 5.68.0 / 5.72.0
error: cannot lock ref 'refs/remotes/origin/fixDeltaRestore': unable to resolve reference 'refs/remotes/origin/fixDeltaRestore': reference broken
error: cannot lock ref 'refs/remotes/origin/installHostCertificate': unable to resolve reference 'refs/remotes/origin/installHostCertificate': reference broken
error: cannot lock ref 'refs/remotes/origin/listBackupsOnRemoteDataStructure': unable to resolve reference 'refs/remotes/origin/listBackupsOnRemoteDataStructure': reference broken
error: cannot lock ref 'refs/remotes/origin/nr-copy-file-range-merge': unable to resolve reference 'refs/remotes/origin/nr-copy-file-range-merge': reference broken
error: cannot lock ref 'refs/remotes/origin/nr-zfs-sr-type': unable to resolve reference 'refs/remotes/origin/nr-zfs-sr-type': reference broken
error: cannot lock ref 'refs/remotes/origin/rajaa-fix-numberOfSshkeys': unable to resolve reference 'refs/remotes/origin/rajaa-fix-numberOfSshkeys': reference broken
error: cannot lock ref 'refs/remotes/origin/schedulerGranuldarity': unable to resolve reference 'refs/remotes/origin/schedulerGranuldarity': reference broken
error: cannot lock ref 'refs/remotes/origin/sdn-controller-of-bridge': unable to resolve reference 'refs/remotes/origin/sdn-controller-of-bridge': reference broken
error: cannot lock ref 'refs/remotes/origin/self-editVifLockingMode': unable to resolve reference 'refs/remotes/origin/self-editVifLockingMode': reference broken
0 updates available
```
-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```

# systemctl status xo-server.service
● xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-10-22 17:11:38 CDT; 8s ago
   Main PID: 2885 (node)
      Tasks: 18 (limit: 3445)
     Memory: 170.4M
     CGroup: /system.slice/xo-server.service
             ├─2885 /usr/local/bin/node ./bin/xo-server
             └─2913 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/worker>

Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.797Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.797Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.798Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.798Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.852Z xo:plugin INFO successfully r>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.864Z xo:xo-server:sdn-controller:t>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.865Z xo:xo-server:sdn-controller D>
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.865Z xo:plugin INFO successfully r>

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```
 -- Logs begin at Sun 2019-03-03 17:19:51 CST. --
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.568Z xo:plugin INFO register usage-report
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.718Z xo:plugin INFO register web-hooks
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.720Z xo:plugin INFO failed register cloud
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.721Z xo:plugin INFO Cannot find module '/usr/local/lib/node_modules/xo-server-cloud'
Oct 22 17:11:41 ubuntuxo xo-server[2885]: Require stack:
Oct 22 17:11:41 ubuntuxo xo-server[2885]: - /opt/xen-orchestra/packages/xo-server/dist/index.js
Oct 22 17:11:41 ubuntuxo xo-server[2885]: - /opt/xen-orchestra/packages/xo-server/index.js
Oct 22 17:11:41 ubuntuxo xo-server[2885]: - /opt/xen-orchestra/packages/xo-server/bin/xo-server {
Oct 22 17:11:41 ubuntuxo xo-server[2885]:   error: Error: Cannot find module '/usr/local/lib/node_modules/xo-server-cloud'
Oct 22 17:11:41 ubuntuxo xo-server[2885]:   Require stack:
Oct 22 17:11:41 ubuntuxo xo-server[2885]:   - /opt/xen-orchestra/packages/xo-server/dist/index.js
Oct 22 17:11:41 ubuntuxo xo-server[2885]:   - /opt/xen-orchestra/packages/xo-server/index.js
Oct 22 17:11:41 ubuntuxo xo-server[2885]:   - /opt/xen-orchestra/packages/xo-server/bin/xo-server
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Function.Module._load (internal/modules/cjs/loader.js:842:27)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Module.require (internal/modules/cjs/loader.js:1026:19)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at require (internal/modules/cjs/helpers.js:72:18)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Xo.call (/opt/xen-orchestra/packages/xo-server/src/index.js:306:18)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Xo.call (/opt/xen-orchestra/packages/xo-server/src/index.js:364:25)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at map (/opt/xen-orchestra/packages/xo-server/src/index.js:386:38)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Array.map (<anonymous>)
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       at Xo.registerPluginsInPath (/opt/xen-orchestra/packages/xo-server/src/index.js:384:11) {
Oct 22 17:11:41 ubuntuxo xo-server[2885]:     code: 'MODULE_NOT_FOUND',
Oct 22 17:11:41 ubuntuxo xo-server[2885]:     requireStack: [
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       '/opt/xen-orchestra/packages/xo-server/dist/index.js',
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       '/opt/xen-orchestra/packages/xo-server/index.js',
Oct 22 17:11:41 ubuntuxo xo-server[2885]:       '/opt/xen-orchestra/packages/xo-server/bin/xo-server'
Oct 22 17:11:41 ubuntuxo xo-server[2885]:     ]
Oct 22 17:11:41 ubuntuxo xo-server[2885]:   }
Oct 22 17:11:41 ubuntuxo xo-server[2885]: }
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.774Z xo:xo-server:sdn-controller DEBUG No cert-dir provided, using default self-signed certificates
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register auth-github
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register auth-ldap
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register auth-saml
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register test-plugin
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register transport-icinga2
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register transport-nagios
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register transport-slack
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register transport-xmpp
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register web-hooks
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register backup-reports
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.794Z xo:plugin INFO successfully register transport-email
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.797Z xo:plugin INFO successfully register load-balancer
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.797Z xo:plugin INFO successfully register audit
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.798Z xo:plugin INFO successfully register auth-google
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.798Z xo:plugin INFO successfully register perf-alert
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.852Z xo:plugin INFO successfully register usage-report
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.864Z xo:xo-server:sdn-controller:tls-connect DEBUG Certificates have been updated
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.865Z xo:xo-server:sdn-controller DEBUG xapi connected { id: '6f0c52b8-9f18-33e1-4fff-51b2895e4540' }
Oct 22 17:11:41 ubuntuxo xo-server[2885]: 2020-10-22T22:11:41.865Z xo:plugin INFO successfully register sdn-controller
#### Provide answers to these questions:

XO running on ubuntu focal 20.04

**Comment by Jarli01** [comment]
If you haven't already try restarting XO, and then updating.

**Comment by kevdogg** [comment]
Yea I did that a few times -- same error messages

**Comment by Jarli01** [comment]
Okay give me a minute to check something. Usually these are issues that VatesFR needs to address. 

Testing tho

**Comment by Jarli01** [comment]
The cloud plugins are expected to fail (those are only available in the XOA trial or paid versions) otherwise I've been unable to reproduce.

**Comment by Jarli01** [comment]
Ha, while this could be deployed to docker, that isn't something I'd bother with personally. 

Try a clean install on a new VM and just import the settings.

**Comment by kevdogg** [comment]
I just renamed the /opt/xen-orchestra directory and reinstalled after exporting config.  
Seems data stored elsewhere since when I restarted service it just worked without having to import config

I ran updater script after this and the error I posted above wasn't there anymore.

I only hope this wasn't a problem on the installation (only error I received):
  `Error: failed to download version index (https://nodejs.org/dist/index.tab)`

**Comment by Jarli01** [comment]
That's essentially the same thing as using a new build, without reinstalling dependencies. 

If you had any errors it would be wise to just build a new install so you know you're in good shape.
