### ISSUE TITLE
Any xo--update.sh ends with the same message

### ISSUE THREAD

**Issue by beber75** [Jarli01/xenorchestra_updater#45]
#### Expected Behavior

Update my XO version

-----

#### Actual Behavior

When trying to update and I start the command (or any other command from bash):

sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -n lts

I'm ending with the same message:

Incorrect version of Node detected
Update node with the following command and then rerun this script
n lts

-----

#### Confirm XOCE services are running

xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-06-04 17:51:29 UTC; 6min ago
   Main PID: 670 (node)
      Tasks: 11 (limit: 4592)
     Memory: 205.3M
     CGroup: /system.slice/xo-server.service
             └─670 /usr/local/bin/node ./bin/xo-server

Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.501Z xo:plugin INFO successfully register perf-alert
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.545Z xo:xo-server:sdn-controller:tls-connect DEBUG Certificates have been updated
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.545Z xo:plugin INFO successfully register sdn-controller
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.570Z xo:xo-server:sdn-controller DEBUG xapi connected { id: '85b91af3-2d31-9dc1-cbd9-fb40c0795429' }
Jun 04 17:52:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:53:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:54:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:55:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:56:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:57:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!

#### Provide the output of journalctl logs

Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.458Z app-conf /root/.config/xo-server/config.z-auto.json
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.458Z app-conf /opt/xen-orchestra/packages/xo-server/.xo-server.toml
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.503Z xo:mixins:hooks DEBUG start finished
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.504Z xo:mixins:hooks DEBUG clean start…
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.672Z xo:mixins:hooks DEBUG clean finished
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.732Z xo:main INFO Setting up / → /opt/xen-orchestra/packages/xo-web/dist
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.734Z xo:plugin INFO register audit
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.751Z xo:plugin INFO register auth-github
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.767Z xo:plugin INFO register auth-google
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.772Z xo:plugin INFO register auth-ldap
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.825Z xo:plugin INFO register auth-saml
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.933Z xo:plugin INFO register backup-reports
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.937Z xo:plugin INFO register load-balancer
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.950Z xo:plugin INFO register perf-alert
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.953Z xo:plugin INFO register sdn-controller
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.983Z xo:plugin INFO register test-plugin
Jun 04 17:51:33 xenorchestra xo-server[670]: 2021-06-04T17:51:33.984Z xo:plugin INFO register transport-email
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.021Z xo:plugin INFO register transport-icinga2
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.023Z xo:plugin INFO register transport-nagios
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.025Z xo:plugin INFO register transport-slack
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.166Z xo:plugin INFO register transport-xmpp
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.229Z xo:plugin INFO register usage-report
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.379Z xo:plugin INFO register web-hooks
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.473Z xo:xo-server:sdn-controller DEBUG No cert-dir provided, using default self-signed certificates
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register auth-github
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register auth-google
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register auth-ldap
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register auth-saml
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register test-plugin
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register transport-email
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register transport-icinga2
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register transport-nagios
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register transport-slack
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register transport-xmpp
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register usage-report
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.496Z xo:plugin INFO successfully register web-hooks
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.497Z xo:plugin INFO successfully register backup-reports
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.501Z xo:plugin INFO successfully register audit
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.501Z xo:plugin INFO successfully register load-balancer
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.501Z xo:plugin INFO successfully register perf-alert
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.545Z xo:xo-server:sdn-controller:tls-connect DEBUG Certificates have been updated
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.545Z xo:plugin INFO successfully register sdn-controller
Jun 04 17:51:34 xenorchestra xo-server[670]: 2021-06-04T17:51:34.570Z xo:xo-server:sdn-controller DEBUG xapi connected { id: '85b91af3-2d31-9dc1-cbd9-fb40c0795429' }
Jun 04 17:52:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:53:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:54:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:55:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:56:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:57:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!
Jun 04 17:58:00 xenorchestra xo-server[670]: [load-balancer]Execute plans!

 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Upgrade
- Version of XOCE server and web interface you're running xo-server 5.79.2 and xo-web 5.81.0
- What OS is XOCE running on? Ubuntu 20.04.2 LTS
- What method you used to install XOCE (xo_install.sh, manual installation, etc) xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error I'm just trying to update my version.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. I have no errors
- Include what you've done so far in the installation, and if you got any error messages along the way. Installed XO via installation script and on regular basis updateing it via xo-update.sh
- Indicate whether or not you've manually edited any data directly. no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
What version of node do you have installed?

Please run 
`node -v`

You likely have an out of date version

**Comment by beber75** [comment]
It's v14.16.0
I've tried to update my node to stable and lts with the same message

**Comment by Jarli01** [comment]
Interesting, I currently have 14.16.1 (so a minor version ahead of you). If you run the normal update process the system still prints this out?

**Comment by beber75** [comment]
Yes, the same output message

**Comment by Jarli01** [comment]
Is XO no running?

**Comment by beber75** [comment]
Everything is running fine. I mean my webinterface is up, my backup jobs are running fine too.
I'm just unable to update anymore through the script.

**Comment by beber75** [comment]
Should I try a force rebuild ?

**Comment by Jarli01** [comment]
Got it, so that is an issue that you may need to correct through the OS, sudo apt update && sudo apt upgrade

Worse case, you can build a new installation of XOCE using the installation script, and just import the configuration. Everything will move over (including your backups, tasks etc).

**Comment by beber75** [comment]
Well, I alway do a udo apt update && sudo apt upgrade and a reboot before starting the scripted update. I guess I have to reinstall it

**Comment by Jarli01** [comment]
You can certainly give a force rebuild a try, that won't harm anything.  

A critical thing to remember about XO is that it's meant to be disposable. So you can always build a new install, import the configuration and keep moving forward.

**Comment by beber75** [comment]
Thanks, force rebuild ends with the same message.

I'll rebuild a new vm it will be safer.
Thanks for your quick support.

**Comment by Danp2** [comment]
Did you try issuing the command `sudo n lts` directly from the command line? If not, please do that. If yes, then please post the output of `n ls`. FWIW, current LTS is 14.17.0,

**Comment by Danp2** [comment]
@Jarli01 Looks like the recent Node related commit aborts without updating Node. I'll look into that.

**Comment by beber75** [comment]
> 
> 
> Did you try issuing the command `sudo n lts` directly from the command line? If not, please do that. If yes, then please post the output of `n ls`. FWIW, current LTS is 14.17.0,

 sudo n ls
node/12.16.3
node/14.16.0

Strange I have two nodes

**Comment by Danp2** [comment]
@beber75 That's not a problem. Please run `sudo n lts` and then show the output of `n ls` again.

**Comment by beber75** [comment]
Meanwhile I'v deleted the old version 12.16.3

I did a sudo n lts and nos I have 

sudo n ls
node/14.16.0
node/14.17.0

May I delete the 14.16.0 version ?

**Comment by beber75** [comment]
Ok, I've launch an update process and it's compiling

**Comment by Jarli01** [comment]
The old version of node shouldn't be in use, but you really should only have the 1 version at any given time...

**Comment by Danp2** [comment]
@Jarli01 Actually, that's incorrect. You can have multiple versions installed. However, only one is "active" at any given time. You can issue the command `n prune` to remove older versions.

**Comment by beber75** [comment]
I realy did not know how it ended with two versions.

After reboot, my xo-server.service starts but quickly stops 

systemctl status xo-server.service
● xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-06-04 18:53:04 UTC; 13ms ago
   Main PID: 1161 (node)
      Tasks: 7 (limit: 4592)
     Memory: 3.0M
     CGroup: /system.slice/xo-server.service
             └─1161 /usr/local/bin/node ./dist/cli.mjs

Jun 04 18:53:04 xenorchestra systemd[1]: Started XO Server.
deki@xenorchestra:~$ systemctl status xo-server.service
● xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-06-04 18:53:06 UTC; 18s ago
    Process: 1174 ExecStart=/usr/local/bin/node ./dist/cli.mjs (code=exited, status=1/FAILURE)
   Main PID: 1174 (code=exited, status=1/FAILURE)

Jun 04 18:53:06 xenorchestra systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Jun 04 18:53:06 xenorchestra systemd[1]: Stopped XO Server.
Jun 04 18:53:06 xenorchestra systemd[1]: xo-server.service: Start request repeated too quickly.
Jun 04 18:53:06 xenorchestra systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jun 04 18:53:06 xenorchestra systemd[1]: Failed to start XO Server.

I understand It's complicateds to debut like that. Dont worry, I'll try a force rebuild and if it does not help, reinstall a machine

**Comment by beber75** [comment]
Force rebuild bring my server back to life :)

**Comment by Jarli01** [comment]
> @Jarli01 Actually, that's incorrect. You can have multiple versions installed. However, only one is "active" at any given time. You can issue the command `n prune` to remove older versions.

That is what I meant, *you* should be maintaining the health of the system.

**Comment by Danp2** [comment]
@Jarli01 Can you look at the open PR? I haven't tested  the changes yet. Also, it's complaining about a conflict preventing a merge. I moved some code around so maybe that's causing an issue. <shrug>

**Comment by beber75** [comment]
Thank you (and sorry for my english (I'm french)).
