### ISSUE TITLE
PR review request

### ISSUE THREAD

**Issue by Jarli01** [Jarli01/xenorchestra_updater#47]
@Jarli01 Can you look at the open PR? I haven't tested  the changes yet. Also, it's complaining about a conflict preventing a merge. I moved some code around so maybe that's causing an issue. <shrug>

_Originally posted by @Danp2 in https://github.com/Jarli01/xenorchestra_updater/issues/45#issuecomment-854940263_

**Comment by Jarli01** [comment]
@Danp2 which change specifically were you trying to correct? Also was there really a need to rearrange the entire thing... ;)

**Comment by Danp2** [comment]
Let's stick to one discussion. Moving to PR.
