### ISSUE TITLE
xo-server does not start after update (incl node update)

### ISSUE THREAD

**Issue by BerT666** [Jarli01/xenorchestra_updater#51]
#### Expected Behavior

xo-server starts after Update ( Update done via CLI )

-----

#### Actual Behavior

xo-server does not start
[ this seems to be related to an update of node ]
Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'

-----

#### Confirm XOCE services are running

 xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-07-14 09:12:36 UTC; 6min ago
   Main PID: 426591 (code=exited, status=1/FAILURE)

Jul 14 09:12:36 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Jul 14 09:12:36 xoa systemd[1]: Stopped XO Server.
Jul 14 09:12:36 xoa systemd[1]: xo-server.service: Start request repeated too quickly.
Jul 14 09:12:36 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jul 14 09:12:36 xoa systemd[1]: Failed to start XO Server.

#### Provide the output of journalctl logs

Jul 14 09:12:35 xoa xo-server[426577]: internal/modules/cjs/loader.js:905
Jul 14 09:12:35 xoa xo-server[426577]:   throw err;
Jul 14 09:12:35 xoa xo-server[426577]:   ^
Jul 14 09:12:35 xoa xo-server[426577]: Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'
Jul 14 09:12:35 xoa xo-server[426577]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
Jul 14 09:12:35 xoa xo-server[426577]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
Jul 14 09:12:35 xoa xo-server[426577]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Jul 14 09:12:35 xoa xo-server[426577]:     at internal/main/run_main_module.js:17:47 {
Jul 14 09:12:35 xoa xo-server[426577]:   code: 'MODULE_NOT_FOUND',
Jul 14 09:12:35 xoa xo-server[426577]:   requireStack: []
Jul 14 09:12:35 xoa xo-server[426577]: }
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 3.
Jul 14 09:12:35 xoa systemd[1]: Stopped XO Server.
Jul 14 09:12:35 xoa systemd[1]: Started XO Server.
Jul 14 09:12:35 xoa xo-server[426584]: internal/modules/cjs/loader.js:905
Jul 14 09:12:35 xoa xo-server[426584]:   throw err;
Jul 14 09:12:35 xoa xo-server[426584]:   ^
Jul 14 09:12:35 xoa xo-server[426584]: Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'
Jul 14 09:12:35 xoa xo-server[426584]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
Jul 14 09:12:35 xoa xo-server[426584]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
Jul 14 09:12:35 xoa xo-server[426584]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Jul 14 09:12:35 xoa xo-server[426584]:     at internal/main/run_main_module.js:17:47 {
Jul 14 09:12:35 xoa xo-server[426584]:   code: 'MODULE_NOT_FOUND',
Jul 14 09:12:35 xoa xo-server[426584]:   requireStack: []
Jul 14 09:12:35 xoa xo-server[426584]: }
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
Jul 14 09:12:35 xoa systemd[1]: Stopped XO Server.
Jul 14 09:12:35 xoa systemd[1]: Started XO Server.
Jul 14 09:12:35 xoa xo-server[426591]: internal/modules/cjs/loader.js:905
Jul 14 09:12:35 xoa xo-server[426591]:   throw err;
Jul 14 09:12:35 xoa xo-server[426591]:   ^
Jul 14 09:12:35 xoa xo-server[426591]: Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'
Jul 14 09:12:35 xoa xo-server[426591]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
Jul 14 09:12:35 xoa xo-server[426591]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
Jul 14 09:12:35 xoa xo-server[426591]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Jul 14 09:12:35 xoa xo-server[426591]:     at internal/main/run_main_module.js:17:47 {
Jul 14 09:12:35 xoa xo-server[426591]:   code: 'MODULE_NOT_FOUND',
Jul 14 09:12:35 xoa xo-server[426591]:   requireStack: []
Jul 14 09:12:35 xoa xo-server[426591]: }
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 09:12:35 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jul 14 09:12:36 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Jul 14 09:12:36 xoa systemd[1]: Stopped XO Server.
Jul 14 09:12:36 xoa systemd[1]: xo-server.service: Start request repeated too quickly.
Jul 14 09:12:36 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
Jul 14 09:12:36 xoa systemd[1]: Failed to start XO Server.

 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade

- Version of XOCE server and web interface you're running
(happens after update to latest "stable" release)

- What OS is XOCE running on?
Ubuntu 20.04.2 LTS

- What method you used to install XOCE (xo_install.sh, manual installation, etc)
xo-install.sh

- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
all since xo-server does not start

- Any errors that appear in your browser's error console. ( "Page not found")1
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Danp2** [comment]
What version of Node are you running? (show the output of `node -v`) It should be at least v14.17

**Comment by Jarli01** [comment]
Just checking to see if you still needed assistance.

**Comment by BerT666** [comment]
before update it is :
node -v
v14.17.1 (Update script wants node update)...

after node upgrade [ sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -n stable] :
node -v
v14.17.3
=> xoa does not start after updating.

It looks like the xoa cannot start whith node v 14.17.3.
I tried a "forced rebuild" but it did not help.

Any hint would be great ;-) ( ATM I am totally happy that my xoa does have snapshots...)

Best BerT

**Comment by Danp2** [comment]
Technically, the script tells you to run `n lts` to bring node into compliance. I haven't tested the method you used,.

Have you tried manually building with yarn now that the correct version of node is installed?

```'
sudo bash
cd /opt/xen-orchestra/
yarn; yarn build
```

**Comment by BerT666** [comment]
Now it is working again...
I updated node ( n lts), did a yarn & yarn build (WebUI still OK).
rebooted the VM, upgraded xoa ( curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f ) and all was OK.

Seems that I had to update first node, then do a yarn(build) and afterwards update the xoa...

Thanks a lot for the help!
