### ISSUE TITLE
Problem with performing installation

### ISSUE THREAD

**Issue by byt3c** [Jarli01/xenorchestra_updater#53]
Hi all, 
Let me provide some background. I set up XOCE instance bu hand several months ago and i've been running it sucessfully since. Unfortunatelly i deleted snapshots which held last working version, and have not created snapshot before upgrading. After manual upgrade yarn returned "platform incompatibility warnings and linux bin was gone from xoce builds. 

So i tried running your installer script.

	root@XOCE:/home/xen-orchestra# ./xo_install.sh
	Get:1 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
	Hit:2 http://security.debian.org/debian-security buster/updates InRelease
	Get:3 http://ftp.agh.edu.pl/debian buster InRelease [122 kB]
	Err:1 https://dl.yarnpkg.com/debian stable InRelease
	The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
	Get:4 http://ftp.agh.edu.pl/debian buster-updates InRelease [51.9 kB]
	Reading package lists... Done
	W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
	E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
	N: Updating from such a repository can't be done securely, and is therefore disabled by default.
	N: See apt-secure(8) manpage for repository creation and user configuration details.
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	git is already the newest version (1:2.20.1-2+deb10u3).
	gnupg is already the newest version (2.2.12-1+deb10u1).
	gnupg set to manually installed.
	The following packages were automatically installed and are no longer required:
	libbrotli1 libc-ares2 libnode64 libuv1 nodejs-doc
	Use 'apt autoremove' to remove them.
	The following additional packages will be installed:
	libcurl4
	The following NEW packages will be installed:
	apt-transport-https curl libcurl4
	0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.
	Need to get 746 kB of archives.
	After this operation, 1,281 kB of additional disk space will be used.
	Get:1 http://ftp.agh.edu.pl/debian buster/main amd64 apt-transport-https all 1.8.2.3 [149 kB]
	Get:2 http://ftp.agh.edu.pl/debian buster/main amd64 libcurl4 amd64 7.64.0-4+deb10u2 [332 kB]
	Get:3 http://ftp.agh.edu.pl/debian buster/main amd64 curl amd64 7.64.0-4+deb10u2 [265 kB]
	Fetched 746 kB in 0s (2,104 kB/s)
	Selecting previously unselected package apt-transport-https.
	(Reading database ... 36393 files and directories currently installed.)
	Preparing to unpack .../apt-transport-https_1.8.2.3_all.deb ...
	Unpacking apt-transport-https (1.8.2.3) ...
	Selecting previously unselected package libcurl4:amd64.
	Preparing to unpack .../libcurl4_7.64.0-4+deb10u2_amd64.deb ...
	Unpacking libcurl4:amd64 (7.64.0-4+deb10u2) ...
	Selecting previously unselected package curl.
	Preparing to unpack .../curl_7.64.0-4+deb10u2_amd64.deb ...
	Unpacking curl (7.64.0-4+deb10u2) ...
	Setting up apt-transport-https (1.8.2.3) ...
	Setting up libcurl4:amd64 (7.64.0-4+deb10u2) ...
	Setting up curl (7.64.0-4+deb10u2) ...
	Processing triggers for man-db (2.8.5-2) ...
	Processing triggers for libc-bin (2.28-10) ...
	OK
	deb https://dl.yarnpkg.com/debian/ stable main
	Hit:1 http://security.debian.org/debian-security buster/updates InRelease
	Get:2 http://ftp.agh.edu.pl/debian buster InRelease [122 kB]
	Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
	Get:4 http://ftp.agh.edu.pl/debian buster-updates InRelease [51.9 kB]
	Get:5 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.1 kB]
	Get:6 https://dl.yarnpkg.com/debian stable/main all Packages [10.1 kB]
	Fetched 194 kB in 1s (338 kB/s)
	Reading package lists... Done
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	The following packages were automatically installed and are no longer required:
	libyaml-0-2 python-chardet python-cliapp python-markdown python-pkg-resources python-pygments python-ttystatus
	python-yaml
	Use 'apt autoremove' to remove them.
	The following additional packages will be installed:
	nodejs
	Suggested packages:
	npm
	The following packages will be REMOVED:
	cmdtest
	The following NEW packages will be installed:
	nodejs yarn
	0 upgraded, 2 newly installed, 1 to remove and 1 not upgraded.
	Need to get 891 kB/979 kB of archives.
	After this operation, 5,469 kB of additional disk space will be used.
	Get:1 https://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.5-1 [891 kB]
	Fetched 891 kB in 0s (4,650 kB/s)
	(Reading database ... 36412 files and directories currently installed.)
	Removing cmdtest (0.32-3) ...
	Selecting previously unselected package nodejs.
	(Reading database ... 36387 files and directories currently installed.)
	Preparing to unpack .../nodejs_10.24.0dfsg-1deb10u1_amd64.deb ...
	Unpacking nodejs (10.24.0dfsg-1deb10u1) ...
	Selecting previously unselected package yarn.
	Preparing to unpack .../archives/yarn_1.22.5-1_all.deb ...
	Unpacking yarn (1.22.5-1) ...
	Setting up nodejs (10.24.0dfsg-1deb10u1) ...
	update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
	Setting up yarn (1.22.5-1) ...
	Processing triggers for man-db (2.8.5-2) ...
	% Total % Received % Xferd Average Speed Time Time Time Current
	Dload Upload Total Spent Left Speed
	100 46156 100 46156 0 0 186k 0 --:--:-- --:--:-- --:--:-- 185k
	installing : node-v14.17.4
	mkdir : /usr/local/n/versions/node/14.17.4
	fetch : https://nodejs.org/dist/v14.17.4/node-v14.17.4-linux-x64.tar.xz
	installed : v14.17.4 (with npm 6.14.14)

	Note: the node command changed location and the old location may be remembered in your current shell.
	old : /usr/bin/node
	new : /usr/local/bin/node
	To reset the command location hash either start a new shell, or execute PATH="$PATH"
	ln: failed to create symbolic link '/usr/local/bin/node': File exists
	Reading package lists... Done
	Building dependency tree
	Reading state information... Done
	build-essential is already the newest version (12.6).
	cifs-utils is already the newest version (2:6.8-2).
	git is already the newest version (1:2.20.1-2+deb10u3).
	libpng-dev is already the newest version (1.6.36-6).
	libvhdi-utils is already the newest version (20181227-1).
	lvm2 is already the newest version (2.03.02-3).
	python3-minimal is already the newest version (3.7.3-1).
	python3-minimal set to manually installed.
	redis-server is already the newest version (5:5.0.3-4+deb10u3).
	The following packages were automatically installed and are no longer required:
	libyaml-0-2 python-chardet python-cliapp python-markdown python-pkg-resources python-pygments python-ttystatus
	python-yaml
	Use 'apt autoremove' to remove them.
	The following additional packages will be installed:
	keyutils libevent-2.1-6 libnfsidmap2 libtirpc-common libtirpc3 rpcbind
	Suggested packages:
	open-iscsi watchdog
	The following NEW packages will be installed:
	keyutils libevent-2.1-6 libnfsidmap2 libtirpc-common libtirpc3 nfs-common rpcbind
	0 upgraded, 7 newly installed, 0 to remove and 1 not upgraded.
	Need to get 649 kB of archives.
	After this operation, 1,930 kB of additional disk space will be used.
	Get:1 http://ftp.agh.edu.pl/debian buster/main amd64 keyutils amd64 1.6-6 [51.7 kB]
	Get:2 http://ftp.agh.edu.pl/debian buster/main amd64 libevent-2.1-6 amd64 2.1.8-stable-4 [177 kB]
	Get:3 http://ftp.agh.edu.pl/debian buster/main amd64 libnfsidmap2 amd64 0.25-5.1 [32.0 kB]
	Get:4 http://ftp.agh.edu.pl/debian buster/main amd64 libtirpc-common all 1.1.4-0.4 [16.7 kB]
	Get:5 http://ftp.agh.edu.pl/debian buster/main amd64 libtirpc3 amd64 1.1.4-0.4 [93.5 kB]
	Get:6 http://ftp.agh.edu.pl/debian buster/main amd64 rpcbind amd64 1.2.5-0.3+deb10u1 [47.1 kB]
	Get:7 http://ftp.agh.edu.pl/debian buster/main amd64 nfs-common amd64 1:1.3.4-2.5+deb10u1 [231 kB]
	Fetched 649 kB in 1s (1,213 kB/s)
	Selecting previously unselected package keyutils.
	(Reading database ... 36417 files and directories currently installed.)
	Preparing to unpack .../0-keyutils_1.6-6_amd64.deb ...
	Unpacking keyutils (1.6-6) ...
	Selecting previously unselected package libevent-2.1-6:amd64.
	Preparing to unpack .../1-libevent-2.1-6_2.1.8-stable-4_amd64.deb ...
	Unpacking libevent-2.1-6:amd64 (2.1.8-stable-4) ...
	Selecting previously unselected package libnfsidmap2:amd64.
	Preparing to unpack .../2-libnfsidmap2_0.25-5.1_amd64.deb ...
	Unpacking libnfsidmap2:amd64 (0.25-5.1) ...
	Selecting previously unselected package libtirpc-common.
	Preparing to unpack .../3-libtirpc-common_1.1.4-0.4_all.deb ...
	Unpacking libtirpc-common (1.1.4-0.4) ...
	Selecting previously unselected package libtirpc3:amd64.
	Preparing to unpack .../4-libtirpc3_1.1.4-0.4_amd64.deb ...
	Unpacking libtirpc3:amd64 (1.1.4-0.4) ...
	Selecting previously unselected package rpcbind.
	Preparing to unpack .../5-rpcbind_1.2.5-0.3+deb10u1_amd64.deb ...
	Unpacking rpcbind (1.2.5-0.3+deb10u1) ...
	Selecting previously unselected package nfs-common.
	Preparing to unpack .../6-nfs-common_1%3a1.3.4-2.5+deb10u1_amd64.deb ...
	Unpacking nfs-common (1:1.3.4-2.5+deb10u1) ...
	Setting up libtirpc-common (1.1.4-0.4) ...
	Setting up libevent-2.1-6:amd64 (2.1.8-stable-4) ...
	Setting up keyutils (1.6-6) ...
	Setting up libnfsidmap2:amd64 (0.25-5.1) ...
	Setting up libtirpc3:amd64 (1.1.4-0.4) ...
	Setting up rpcbind (1.2.5-0.3+deb10u1) ...
	Created symlink /etc/systemd/system/multi-user.target.wants/rpcbind.service → /lib/systemd/system/rpcbind.service.
	Created symlink /etc/systemd/system/sockets.target.wants/rpcbind.socket → /lib/systemd/system/rpcbind.socket.
	Setting up nfs-common (1:1.3.4-2.5+deb10u1) ...

	Creating config file /etc/idmapd.conf with new version
	Adding system user statd' (UID 108) ... Adding new user statd' (UID 108) with group nogroup' ... Not creating home directory /var/lib/nfs'.
	Created symlink /etc/systemd/system/multi-user.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
	Created symlink /etc/systemd/system/remote-fs.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
	nfs-utils.service is a disabled or a static unit, not starting it.
	Processing triggers for systemd (241-7~deb10u8) ...
	Processing triggers for man-db (2.8.5-2) ...
	Processing triggers for libc-bin (2.28-10) ...
	Cloning into 'xen-orchestra'...
	remote: Enumerating objects: 98521, done.
	remote: Counting objects: 100% (5348/5348), done.
	remote: Compressing objects: 100% (1826/1826), done.
	remote: Total 98521 (delta 3899), reused 4754 (delta 3456), pack-reused 93173
	Receiving objects: 100% (98521/98521), 51.55 MiB | 23.14 MiB/s, done.
	Resolving deltas: 100% (69432/69432), done.
	yarn install v1.22.5
	[1/5] Validating package.json...
	[2/5] Resolving packages...
	[3/5] Fetching packages...
	error An unexpected error occurred: "/usr/local/share/.cache/yarn/v6/npm-caniuse-lite-1.0.30001245-45b941bbd833cb0fa53861ff2bae746b3c6ca5d4-integrity/node_modules/caniuse-lite/.yarn-metadata.json: Unexpected end of JSON input".
	info If you think this is a bug, please open a bug report with the information provided in "/opt/xen-orchestra/yarn-error.log".
	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
	yarn run v1.22.5
	$ scripts/run-script --parallel build
	internal/modules/cjs/loader.js:892
	throw err;
	^

	Error: Cannot find module 'promise-toolbox'
	Require stack:

	/opt/xen-orchestra/scripts/run-script
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
	at Function.Module._load (internal/modules/cjs/loader.js:745:27)
	at Module.require (internal/modules/cjs/loader.js:961:19)
	at require (internal/modules/cjs/helpers.js:92:18)
	at Object. (/opt/xen-orchestra/scripts/run-script:4:32)
	at Module._compile (internal/modules/cjs/loader.js:1072:14)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
	at Module.load (internal/modules/cjs/loader.js:937:32)
	at Function.Module._load (internal/modules/cjs/loader.js:778:12)
	at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
	code: 'MODULE_NOT_FOUND',
	requireStack: [ '/opt/xen-orchestra/scripts/run-script' ]
	}
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
	Ignoring xo-server-test plugin
	Created symlink /etc/systemd/system/multi-user.target.wants/xo-server.service → /lib/systemd/system/xo-server.service.

Installation complete, open a browser to:

- Is this a fresh install or an upgrade? - fresh - overinstall
- Version of XOCE server and web interface you're running - up to date - installed
- What OS is XOCE running on? - debian buster current stable
- What method you used to install XOCE (xo_install.sh, manual installation, etc) - xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error - N/A
- If a stacktrace is provided in the error, include that too. - above
- Any errors that appear in your browser's error console. - pasted above
- Include what you've done so far in the installation, and if you got any error messages along the way. tried to remove old serviecs rebooted, and tried installing from script
- Indicate whether or not you've manually edited any data directly. - no data edited

**Comment by Jarli01** [comment]
This is the updater script you've posted to, since you're reinstalling over an installation you previously performed by hand, I would recommend building a new Ubuntu Server VM (Use XCP-NG Console if you must) and then install using https://github.com/Jarli01/xenorchestra_installer or attempt to import the XOCE Appliance from the install script. 

Additionally, when posting code blocks, please post them indented like I've updated your post, it makes it way easier to read.

**Comment by Jarli01** [comment]
@byt3c are you all set or are you still having issues?

**Comment by byt3c** [comment]
It seems there is bug in XO repository - i'm not able to build it whatever approach i use.  Maybe i need to wait a bit to get newer version.

**Comment by byt3c** [comment]
I tried now, purged cache again and it worked this time. - i have no idea why but it did. despite errors :
`Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
fatal: destination path 'xen-orchestra' already exists and is not an empty directory.
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[#####################--------------------------------------------------------------------------------] 11872/57497`

**Comment by Jarli01** [comment]
Closing this issue for now, good luck.
