### ISSUE TITLE
Backup Restore Not Loading Any Remote Backups 

### ISSUE THREAD

**Issue by stevewest15** [Jarli01/xenorchestra_updater#54]
After a recent update of XOCE using the [xo-update.sh](https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh) , now I can't see any of our backups when I go to the "Restore" tab. I checked to see if this issue can be replicated using the official XO and I can't replicate it. Using the official XO, the Restore tab shows our S3 backups to Backblaze but when I use XOCE, the Restore page doesn't show anything. It used to show up as we use XOCE primarily.

#### Expected Behavior

When I go to Backup > Restore, I should be able to see a full list of backups that can be restored. Here is what the Restore page should display as seen from the official XO (not the community build): https://www.screencast.com/t/muberEdlKcKP

-----

#### Actual Behavior

Using the XOCE w/ the latest build, when I go to Backup > Restore, I don't see any of our remote backups. Tried clicking on "Refresh backup list" doesn't fix the issue. See this screenshot: https://www.screencast.com/t/WvciJ57qe

-----

#### Confirm XOCE services are running

Yes, XOCE is running:
`# systemctl status xo-server.service
● xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-03-07 07:04:35 EST; 16min ago
   Main PID: 9678 (node)
      Tasks: 12 (limit: 19138)
     Memory: 208.9M
        CPU: 2min 39.569s
     CGroup: /system.slice/xo-server.service
             └─9678 /usr/local/bin/node ./dist/cli.mjs

Mar 07 07:05:33 XOCE xo-server[9678]:   }
Mar 07 07:05:33 XOCE xo-server[9678]: }
Mar 07 07:08:25 XOCE xo-server[9678]: 2022-03-07T12:08:25.500Z xo:xo-mixins:backups-ng WARN listVmB>
Mar 07 07:08:25 XOCE xo-server[9678]:   error: Error: more than 1000 objects, unsupported in this i>
Mar 07 07:08:25 XOCE xo-server[9678]:       at S3Handler._list (/opt/xen-orchestra/@xen-orchestra/f>
Mar 07 07:08:25 XOCE xo-server[9678]:       at runMicrotasks (<anonymous>)
Mar 07 07:08:25 XOCE xo-server[9678]:       at processTicksAndRejections (node:internal/process/tas>
Mar 07 07:08:25 XOCE xo-server[9678]:     dir: '/xo-vm-backups'
Mar 07 07:08:25 XOCE xo-server[9678]:   }
Mar 07 07:08:25 XOCE xo-server[9678]: }`

#### Provide the output of journalctl logs

`# journalctl -u xo-server -f -n 50
-- Journal begins at Tue 2021-12-21 01:42:03 EST. --
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.842Z xo:plugin INFO register netbox
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.843Z xo:plugin INFO register perf-alert
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.843Z xo:plugin INFO register sdn-controller
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.844Z xo:plugin INFO register test-plugin
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.844Z xo:plugin INFO register transport-email
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.844Z xo:plugin INFO register transport-icinga2
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.844Z xo:plugin INFO register transport-nagios
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.845Z xo:plugin INFO register transport-slack
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.846Z xo:plugin INFO register transport-xmpp
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.846Z xo:plugin INFO register usage-report
Mar 07 07:04:37 XOCE xo-server[9678]: 2022-03-07T12:04:37.846Z xo:plugin INFO register web-hooks
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register auth-google
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register auth-github
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register auth-saml
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register auth-ldap
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register netbox
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register transport-email
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register transport-icinga2
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register test-plugin
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register transport-nagios
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register transport-xmpp
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register usage-report
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register web-hooks
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register transport-slack
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.549Z xo:plugin INFO successfully register backup-reports
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.597Z xo:plugin INFO successfully register audit
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.597Z xo:plugin INFO successfully register perf-alert
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.597Z xo:plugin INFO successfully register load-balancer
Mar 07 07:04:38 XOCE xo-server[9678]: 2022-03-07T12:04:38.710Z xo:plugin INFO successfully register sdn-controller
Mar 07 07:04:39 XOCE xo-server[9678]: 2022-03-07T12:04:39.704Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55) (1 connected)
Mar 07 07:04:39 XOCE xo-server[9678]: 2022-03-07T12:04:39.719Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55) (2 connected)
Mar 07 07:04:39 XOCE xo-server[9678]: 2022-03-07T12:04:39.726Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55) (1 connected)
Mar 07 07:04:39 XOCE xo-server[9678]: 2022-03-07T12:04:39.781Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55) (0 connected)
Mar 07 07:05:11 XOCE xo-server[9678]: 2022-03-07T12:05:11.903Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55) (1 connected)
Mar 07 07:05:33 XOCE xo-server[9678]: 2022-03-07T12:05:33.589Z xo:xo-mixins:backups-ng WARN listVmBackups for remote b241d7ad-9e91-4763-96a2-0fe0e54e94c7: {
Mar 07 07:05:33 XOCE xo-server[9678]:   error: Error: more than 1000 objects, unsupported in this implementation
Mar 07 07:05:33 XOCE xo-server[9678]:       at S3Handler._list (/opt/xen-orchestra/@xen-orchestra/fs/src/s3.js:199:21)
Mar 07 07:05:33 XOCE xo-server[9678]:       at runMicrotasks (<anonymous>)
Mar 07 07:05:33 XOCE xo-server[9678]:       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
Mar 07 07:05:33 XOCE xo-server[9678]:     dir: '/xo-vm-backups'
Mar 07 07:05:33 XOCE xo-server[9678]:   }
Mar 07 07:05:33 XOCE xo-server[9678]: }
Mar 07 07:08:25 XOCE xo-server[9678]: 2022-03-07T12:08:25.500Z xo:xo-mixins:backups-ng WARN listVmBackups for remote b241d7ad-9e91-4763-96a2-0fe0e54e94c7: {
Mar 07 07:08:25 XOCE xo-server[9678]:   error: Error: more than 1000 objects, unsupported in this implementation
Mar 07 07:08:25 XOCE xo-server[9678]:       at S3Handler._list (/opt/xen-orchestra/@xen-orchestra/fs/src/s3.js:199:21)
Mar 07 07:08:25 XOCE xo-server[9678]:       at runMicrotasks (<anonymous>)
Mar 07 07:08:25 XOCE xo-server[9678]:       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
Mar 07 07:08:25 XOCE xo-server[9678]:     dir: '/xo-vm-backups'
Mar 07 07:08:25 XOCE xo-server[9678]:   }
Mar 07 07:08:25 XOCE xo-server[9678]: }`

#### What version of Node are you running?

```node -v```<br> 
Node v16.14.0
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of XOCE server and web interface you're running
xo-server 5.89.0 and xo-web 5.94.0
- What OS is XOCE running on?
Debian 5.10.92-1
- What method you used to install XOCE (xo_install.sh, manual installation, etc)
xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
Backup > Restore page doesn't display list of successful backups
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Console shows this error: You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Performed routine OS updates (ie apt-get update and apt-get dist-upgrade)
- Indicate whether or not you've manually edited any data directly.
Only edited /etc/network/interfaces to set eth0

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Danp2** [comment]
Hi Steve,

There have been similar issues reported on the forum. For example, see [here](https://xcp-ng.org/forum/topic/5536/backup-started-to-fail?_=1646656917721). I'm not sure how we can help you to resolve this issue. One thought is to revert to the commit that matches the latest XOA release, which should eliminate the issue if it is caused by a newer commit.

Regards,

Dan

**Comment by stevewest15** [comment]
Hi Dan,

Thank you for your assistance! I just fired up an older version of XOA and didn't see this issue. After updating XOA to latest version, this issue can be reproduced in XOA. I've posted an [update on the forum](https://xcp-ng.org/forum/post/47483) as it seems this is an issue w/ one of the recent updates of XOA.

Thank you again!

Best Regards,

SW
