### ISSUE TITLE
Running updater script on Ubuntu 22.04 receive warning about use of apt-key being deprecated

### ISSUE THREAD

**Issue by kevdogg** [Jarli01/xenorchestra_updater#55]
I'm running xo updater script now on Ubuntu 22.04

On line 197 the updater script, there is the following:

`        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`

I receive the following:

```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
```

I'm not exactly sure the work around however I had to add the following when configuring apt to work with the yarn keys:
```
sudo curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list > /dev/null
```
If I added these as a source, then I could exclude line 197 from the script.  I'm not exactly sure the ramifications of adding something similar to the script.

**Comment by Danp2** [comment]
Thanks for the report. We will look into this further, but that line is really only needed when installing yarn. It was previously moved so that it ran every time to avoid an issue with an expired key.

**Comment by Danp2** [comment]
@kevdogg I applied the fix to the updater script. Please retest and let me know if you encounter any issues.

**Comment by kevdogg** [comment]
@Danp2 

Thanks for update.  I'm going to close the issue.  Things seems t work on my end.
