### ISSUE TITLE
Xen Orchestra stopped working after running the upgrade script

### ISSUE THREAD

**Issue by marianoda** [Jarli01/xenorchestra_updater#59]
jun 21 15:40:19 xoa systemd[1]: Started XO Server.
jun 21 15:40:20 xoa xo-server[18827]: node:internal/modules/cjs/loader:933
jun 21 15:40:20 xoa xo-server[18827]:   const err = new Error(message);
jun 21 15:40:20 xoa xo-server[18827]:               ^
jun 21 15:40:20 xoa xo-server[18827]: Error: Cannot find module './_AggregateError.js'
jun 21 15:40:20 xoa xo-server[18827]: Require stack:
jun 21 15:40:20 xoa xo-server[18827]: - /opt/xen-orchestra/@xen-orchestra/xapi/sr.js
jun 21 15:40:20 xoa xo-server[18827]: - /opt/xen-orchestra/@xen-orchestra/xapi/index.js
jun 21 15:40:20 xoa xo-server[18827]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
jun 21 15:40:20 xoa xo-server[18827]:     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
jun 21 15:40:20 xoa xo-server[18827]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
jun 21 15:40:20 xoa xo-server[18827]:     at require (node:internal/modules/cjs/helpers:102:18)
jun 21 15:40:20 xoa xo-server[18827]:     at Object.<anonymous> (/opt/xen-orchestra/@xen-orchestra/xapi/sr.js:10:24)
jun 21 15:40:20 xoa xo-server[18827]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
jun 21 15:40:20 xoa xo-server[18827]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
jun 21 15:40:20 xoa xo-server[18827]:     at Module.load (node:internal/modules/cjs/loader:981:32)
jun 21 15:40:20 xoa xo-server[18827]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
jun 21 15:40:20 xoa xo-server[18827]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
jun 21 15:40:20 xoa xo-server[18827]:     at require (node:internal/modules/cjs/helpers:102:18)
jun 21 15:40:20 xoa xo-server[18827]:     at Object.<anonymous> (/opt/xen-orchestra/@xen-orchestra/xapi/index.js:234:7)
jun 21 15:40:20 xoa xo-server[18827]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
jun 21 15:40:20 xoa xo-server[18827]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
jun 21 15:40:20 xoa xo-server[18827]:     at Module.load (node:internal/modules/cjs/loader:981:32)
jun 21 15:40:20 xoa xo-server[18827]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
jun 21 15:40:20 xoa xo-server[18827]:   code: 'MODULE_NOT_FOUND',
jun 21 15:40:20 xoa xo-server[18827]:   requireStack: [
jun 21 15:40:20 xoa xo-server[18827]:     '/opt/xen-orchestra/@xen-orchestra/xapi/sr.js',
jun 21 15:40:20 xoa xo-server[18827]:     '/opt/xen-orchestra/@xen-orchestra/xapi/index.js'
jun 21 15:40:20 xoa xo-server[18827]:   ]
jun 21 15:40:20 xoa xo-server[18827]: }
jun 21 15:40:20 xoa systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
jun 21 15:40:20 xoa systemd[1]: xo-server.service: Failed with result 'exit-code'.
jun 21 15:40:20 xoa systemd[1]: xo-server.service: Consumed 1.450s CPU time.
jun 21 15:40:21 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
jun 21 15:40:21 xoa systemd[1]: Stopped XO Server.
jun 21 15:40:21 xoa systemd[1]: xo-server.service: Consumed 1.450s CPU time.

**Comment by Danp2** [comment]
Reported --> https://github.com/vatesfr/xen-orchestra/commit/b12c1794702801f047bc7d61fb461f25a269d5b0#r76646118
