### ISSUE TITLE
XO Not launching after update

### ISSUE THREAD

**Issue by aidanwardman** [Jarli01/xenorchestra_updater#65]
#### Expected Behavior

XO Launches correctly after running update script

-----

#### Actual Behavior

XO attempts to launch but fails given missing node module ProxyAgent.

Managed to manually resolve this issue by running ```npm install``` in the xo-server directory to get ProxyAgent to install.
Worked fine after that.

-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```

#### What version of Node are you running?

v18.19.0
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of XOCE server and web interface you're running. Xen Orchestra, commit [41ed5]
- What OS is XOCE running on? Ubuntu
- What method you used to install XOCE (xo_install.sh, manual installation, etc) Jarli01 install script
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error. N/A
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. 
- Indicate whether or not you've manually edited any data directly. N/A

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Danp2** [comment]
Are you able to replicate this upgrade failure? Here's my observations after taking a quick look at the XO source --

- An update was performed last week to utilize a newer version of the package `proxy-agent`
- This package was added to the overall codebase back in Oct 2021

Based on your description and the above analysis, I don't believe this failure was due to a fault in this script. FWIW, my recent update attempts have all run without issue.

**Comment by Jarli01** [comment]
Answering before Christmas, Dan you Rock!

Happy Holidays!

**Comment by aidanwardman** [comment]
As I got the upgrade working by running ```npm install``` I've had no need to replicate the upgrade steps, My apologies.

I notice it runs ```yarn``` which I assume would install these dependencies, but there's been bugs in yarn before, could this be a similar issue?

https://github.com/yarnpkg/yarn/issues/2240

**Comment by Danp2** [comment]
Closing as this appears to be an isolated incident. Let us know if you encounter this issue again. FWIW, I often will take a snapshot before performing an upgrade, which allows me to quickly restore / test any upgrade issues.
