### ISSUE TITLE
After upgrade from 5.118.0 to 5.135.0 , xo-server no longer starts. ProxyAgent not found.

### ISSUE THREAD

**Issue by davidc0le** [Jarli01/xenorchestra_updater#67]
#### Expected Behavior

After running xo-update.sh, expected the service to be running with the newer version of XO.

#### Actual Behavior

<pre>
Feb 02 14:16:30 xo systemd[1]: Started XO Server.
Feb 02 14:16:31 xo xo-server[1518]: file:///opt/xen-orchestra/packages/xen-api/index.mjs:15
Feb 02 14:16:31 xo xo-server[1518]: import { ProxyAgent } from 'proxy-agent'
Feb 02 14:16:31 xo xo-server[1518]:          ^^^^^^^^^^
Feb 02 14:16:31 xo xo-server[1518]: SyntaxError: Named export 'ProxyAgent' not found. The requested module 'proxy-agent' is a CommonJS module, which may not support all module.exports as named expo>
Feb 02 14:16:31 xo xo-server[1518]: CommonJS modules can always be imported via the default export, for example using:
Feb 02 14:16:31 xo xo-server[1518]: import pkg from 'proxy-agent';
Feb 02 14:16:31 xo xo-server[1518]: const { ProxyAgent } = pkg;
Feb 02 14:16:31 xo xo-server[1518]:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
Feb 02 14:16:31 xo xo-server[1518]:     at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
Feb 02 14:16:31 xo xo-server[1518]:     at async Promise.all (index 0)
Feb 02 14:16:31 xo xo-server[1518]:     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
Feb 02 14:16:31 xo xo-server[1518]:     at async loadESM (node:internal/process/esm_loader:91:5)
Feb 02 14:16:31 xo xo-server[1518]:     at async handleMainPromise (node:internal/modules/run_main:65:12)
Feb 02 14:16:31 xo systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Feb 02 14:16:31 xo systemd[1]: xo-server.service: Failed with result 'exit-code'.
Feb 02 14:16:31 xo systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Feb 02 14:16:31 xo systemd[1]: Stopped XO Server.
Feb 02 14:16:31 xo systemd[1]: xo-server.service: Start request repeated too quickly.
Feb 02 14:16:31 xo systemd[1]: xo-server.service: Failed with result 'exit-code'.
Feb 02 14:16:31 xo systemd[1]: Failed to start XO Server.
</pre>

Retrying the systemd service did not help.

#### Confirm XOCE services are running

SystemD service won't start. Restart tried and not helping.

#### Provide the output of journalctl logs

Pasted above.

#### What version of Node are you running?

v16.20.1
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  
Upgrade
- Version of XOCE server and web interface you're running
Was running xo-server 5.118.0 before upgrade.
- What OS is XOCE running on?
Ubuntu 20.04
- What method you used to install XOCE (xo_install.sh, manual installation, etc) 
 xo_server.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
N/A - no errors or stacktraces from software. 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly.
No data manually edited.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
Your node version is very out of date, you should be using 18.19.0 

Try updating Node first, then attempt this update again

**Comment by Jarli01** [comment]
Additionally, Your OS is out of date. 

It might be faster to just restore your snapshot, then export the configuration and build a new XO installation. Import the configuration and decommission this instance.

**Comment by Jarli01** [comment]
No reply, marking closed.
